---
- name: deploying spc 
  hosts: all
  become: yes
  tasks:
  - name: download jar file from jfrog
    get_url:
      url: "https://srikanthvelma.jfrog.io/artifactory/libs-snapshot-local/org/springframework/samples/spring-petclinic/3.0.0-SNAPSHOT/spring-petclinic-3.0.0-20230309.061207-7.jar"
      dest: /home/ubuntu
      url_username: 'velmasrikanth@gmail.com'
      url_password: 'cmVmdGtuOjAxOjE3MDk3MTM0MjQ6ZjBadGVSdFlKWFFxUHdaVnpDVzA2T3NXMThF'
      mode: '0777'
  - name: copy spc service file
    copy:
      src: spc.service
      dest: /etc/systemd/system/
      mode: '0777'
  - name: start service file
    systemd:
      name: spc.service
      daemon_reload: yes
      enabled: yes
      state: started
  